<a href="https://colab.research.google.com/github/ArchitGupta16/Housing-Price-Prediction/blob/main/Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Scaling

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import numpy as np

train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')
variables = ["LotArea", "BsmtFinSF1", "TotalBsmtSF", "X1stFlrSF", "X2ndFlrSF", "GrLivArea", "GarageArea"]


standard_scaler = StandardScaler()

for variable in variables:
    train_data[variable] = (train_data[variable] - train_data[variable].mean()) / train_data[variable].std()
    test_data[variable] = (test_data[variable] - test_data[variable].mean()) / test_data[variable].std()
test_data.to_csv('normalized_test.csv',index=False)
train_data.to_csv('normalized_train.csv',index=False)


In [ ]:
#@title Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error,mean_squared_log_error,log_loss


In [ ]:
train_data = pd.read_csv('normalized_train.csv')
test_data = pd.read_csv('normalized_test.csv')

Random Forest


In [ ]:
X_train = train_data.drop('SalePrice', axis=1)
y_train = train_data['SalePrice']

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [ ]:
model = RandomForestRegressor(
)
model.fit(X_train, y_train)

RandomForestRegressor()

In [ ]:
y_val_pred = model.predict(X_val)

mse = mean_squared_error(y_val, y_val_pred)
mae = mean_absolute_error(y_val, y_val_pred)
msle = mean_squared_log_error(y_val,y_val_pred)
r2 = r2_score(y_val,y_val_pred)
print("Mean Squared Error (MSE) on validation set:", mse)
print("Mean Absolute Error (MAE) on validation set:", mae)
print("mean log squre error",msle,r2)

Mean Squared Error (MSE) on validation set: 764080205.5901656
Mean Absolute Error (MAE) on validation set: 17048.133630136985
mean log squre error 0.022630868280457083 0.9003849138939855


In [ ]:
y_test_pred = model.predict(test_data)

In [ ]:
y_test_pred

array([126620.16, 152158.25, 181111.72, ..., 153776.44, 119376.  ,
       234777.4 ])

In [ ]:
output_data = pd.DataFrame({'Id': test_data['Id'], 'SalePrice': y_test_pred})
output_data.to_csv('output.csv', index=False)

XGBoost


In [ ]:
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,mean_squared_log_error


In [ ]:
train_data = pd.read_csv('scaled_train.csv')
test_data = pd.read_csv('scaled_test.csv')

In [ ]:
X_train = train_data.drop(['SalePrice'], axis=1)
y_train = train_data['SalePrice']

In [ ]:
xgb_model = xgb.XGBRegressor()
xgb_model.fit(X_train, y_train)

In [ ]:
predictions = xgb_model.predict(test_data)

In [ ]:
output_data = pd.DataFrame({'Id': test_data['Id'], 'SalePrice': predictions})
output_data.to_csv('output.csv', index=False)

In [ ]:
from sklearn.metrics import mean_squared_error,r2_score, mean_absolute_error, mean_squared_error

X = X_train
y = y_train
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

xgb_model = xgb.XGBRegressor()

xgb_model.fit(X_train, y_train)

# Make predictions on the validation set
predictions = xgb_model.predict(X_val)

# Calculate the mean squared error (MSE) as a score
mse = mean_squared_error(y_val, predictions)
score = 1 - mse
print('Model Score:', score)

r2 = r2_score(y_val, predictions)
print('R^2 Score:', r2)

rmse = mean_squared_error(y_val, predictions, squared=False)
print('Root Mean Squared Error:', rmse)

msle = mean_squared_log_error(y_val,predictions)

print("mean log squre error",msle)

Model Score: -691687949.4764657
R^2 Score: 0.9098228769164535
Root Mean Squared Error: 26299.96103564539
mean log squre error 0.021872524522022787


Linear Regression


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

X_train = train_data.drop('SalePrice', axis=1)
y_train = train_data['SalePrice']

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

# Evaluate the model on the validation set
y_val_pred = model.predict(X_val)

mse = mean_squared_error(y_val, y_val_pred)
mae = mean_absolute_error(y_val, y_val_pred)

print("Mean Squared Error (MSE) on validation set:", mse)
print("Mean Absolute Error (MAE) on validation set:", mae)

# Make predictions on the test set
y_test_pred = model.predict(test_data)


Mean Squared Error (MSE) on validation set: 1189172616.3068068
Mean Absolute Error (MAE) on validation set: 21634.18712586914


In [ ]:
output_data = pd.DataFrame({'Id': test_data['Id'], 'SalePrice': y_test_pred})
output_data.to_csv('output.csv', index=False)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import mean_squared_error, mean_absolute_error,r2_score
import tensorflow as tf

# Load the data
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

# Prepare the data
X_train = train_data.drop('SalePrice', axis=1)
y_train = train_data['SalePrice']

X_test = test_data

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)


In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

def rmse_log(y_true, y_pred):
    log_y_true = tf.math.log(y_true)
    log_y_pred = tf.math.log(y_pred)
    return tf.sqrt(tf.reduce_mean(tf.square(log_y_true - log_y_pred)))

# Build the neural network model
model = Sequential()
model.add(Dense(61, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(1))

model.compile(loss='mean_squared_error', optimizer='adam')

model.fit(X_train_scaled, y_train, epochs=150, batch_size=60,verbose=1)

y_val_pred = model.predict(X_val_scaled)


In [ ]:
mse = mean_squared_error(y_val, y_val_pred)
mae = mean_absolute_error(y_val, y_val_pred)

print("Mean Squared Error (MSE) on validation set:", mse)
print("Mean Absolute Error (MAE) on validation set:", mae)

Mean Squared Error (MSE) on validation set: 995487280.696235
Mean Absolute Error (MAE) on validation set: 20839.263083261987


In [ ]:
y_test_pred = model.predict(X_test_scaled)

46/46 [==============================] - 0s 1ms/step


In [ ]:
y_test_pred

array([[193372.22],
       [199128.8 ],
       [223767.38],
       ...,
       [250581.1 ],
       [212003.39],
       [333658.38]], dtype=float32)

In [ ]:
l = []
for i in y_test_pred:
  l.append(i[0])

In [ ]:
output_data = pd.DataFrame({'Id': test_data['Id'], 'SalePrice': l})
output_data.to_csv('output.csv', index=False)

Neural Network


In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import mean_squared_error,r2_score
from tensorflow.keras.callbacks import EarlyStopping


In [ ]:
tf.keras.backend.clear_session()

In [ ]:
def my_loss(y_true, y_pred):
    log_y_true = tf.math.log(y_true)
    log_y_pred = tf.math.log(y_pred)
    return tf.sqrt(tf.reduce_mean(tf.square(log_y_true - log_y_pred)))

In [ ]:
def rmse_log(y_true, y_pred):
    # log_y_true = tf.math.log(y_true)
    # log_y_pred = tf.math.log(y_pred)
    return tf.sqrt(tf.reduce_mean(tf.square(y_true - y_pred)))

train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

y_train = train_data['SalePrice']
X_train = train_data.drop('SalePrice', axis=1)

X_train = X_train.astype('float32')
y_train = y_train.astype('float32')

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(37, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),

    tf.keras.layers.Dense(1)
])

model.compile(optimizer='Nadam', loss=rmse_log)

early_stopping = EarlyStopping(monitor='val_loss', patience=3)

m = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2, callbacks=[early_stopping])
print(m.history['val_loss'])
val_loss = m.history['val_loss'][-1]
print('Validation Loss:', val_loss)

y_val_pred = model.predict(X_train)
print(y_val_pred)
# val_rmse = rmse_log(y_train, y_val_pred)
# print('Validation RMSE:', val_rmse)
r2 = r2_score(y_train,y_val_pred)



In [ ]:
print(my_loss(y_train,y_val_pred))

tf.Tensor(0.5428487, shape=(), dtype=float32)


In [ ]:
model.summary()

In [ ]:
y_test_pred = model.predict(test_data)

46/46 [==============================] - 0s 1ms/step


In [ ]:
y_test_pred

array([[124695.9 ],
       [168292.02],
       [183643.3 ],
       ...,
       [158949.81],
       [ 75820.54],
       [208225.14]], dtype=float32)

In [ ]:
l = []
for i in y_test_pred:
  l.append(i[0])

In [ ]:
output_data = pd.DataFrame({'Id': test_data['Id'], 'SalePrice': l})
output_data.to_csv('output.csv', index=False)